projects:
  eatdish:
    schemaPath: graphql/schema.json
    includes:
      - src/API/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/API
